#!/bin/bash
if [ $# -ne 1 ]; then
	echo "Usage: $0 <newModuleName>"
	exit 1
fi
if [ ! -d "$1" ]; then
	mkdir $1
	echo "#ifndef $1_H" >> $1/$1.h
	echo "#define $1_H" >> $1/$1.h
	echo "" >> $1/$1.h
	echo "" >> $1/$1.h
	echo "" >> $1/$1.h
	echo "#endif" >> $1/$1.h
	echo "#include \"./$1.h\"" >> $1/$1.cpp
	echo "#include \"./$1.h\"" >> $1/$1Test.cpp
	echo "#include \"../utils.h\"" >> $1/$1Test.cpp
else
	exit 0
fi
